# Generated by Django 4.2.5 on 2023-10-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                default="Click Link Above To Read Blog Post...", max_length=264
            ),
        ),
    ]
