# Generated by Django 4.2.5 on 2023-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_post_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
