# Generated by Django 4.2.5 on 2023-10-09 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
