# Generated by Django 4.2.5 on 2023-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
