# Generated by Django 4.2.5 on 2023-10-15 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0021_profile_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                default=0, related_name="blog_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
