# Generated by Django 4.2.5 on 2023-10-15 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0022_post_comments_count_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments_count",
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="blog_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
